name: "Heroku Action"
description: "GitHub Action for deploying on Heroku"
autor: "CDNievas"
branding:
  icon: "stop-circle"
  color: "purple"
inputs:
  heroku_api_key:
    description: "Used for authentication. You can find it in your heroku homepage account settings"
    required: true
  heroku_email:
    description: "Email from Heroku Account"
    required: true
  heroku_app_name:
    description: "The appname to use for deploying/updating"
    required: true
  branch:
    description: "The branch that you would like to deploy to Heroku"
    default: "HEAD"
    required: false
  useforce:
    description: "Set this to true if want to use --force"
    default: false
    required: false
  appdir:
    description: "Set if your app is located in a subdirectory."
    default: ""
    required: false
  procfile:
    description: "Contents of the Procfile to save and deploy"
    required: false
    default: ""
  dynamicFiles:
    description: "Set to true if you need upload files generated dynamically by the GitHub Action to Heroku"
    required: false
    default: false
  buildpacks:
    description: "Buildpacks to install on Heroku"
    required: false
    default: ""
  env_file:
    description: "Path to an localized env file"
    required: false
    default: ""
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: "node12"
  main: "index.js"
